#!/usr/bin/env ruby
require "thor"
require_relative "#{__dir__}/commands/process_contributions"
require_relative "#{__dir__}/commands/get_commits"
class GHCC < Thor
  class_option :verbose, :type => :boolean

  desc "contributions", "Get contributions from user(s)"
  method_option :start_date, :type => :string, default: "#{Date.today - 14}"
  method_option :end_date, :type => :string, default: "#{Date.today}"
  def contributions
    start_date = Date.parse(options[:start_date])
    end_date = Date.parse(options[:end_date])
    get_contributions(start_date, end_date)
  end

  desc "commits", "add commits to contributions"
  method_option :repo, :type => :string, default: "kin/report-service"
  def commits
    repo = options[:repo]
    refresh_commits(repo)
  end
end

GHCC.start(ARGV)
