#!/usr/bin/env ruby
require "thor"
require_relative "#{__dir__}/commands/process_contributions"
require_relative "#{__dir__}/commands/get_commits"
class GHCC < Thor
  # class_option :verbose, :type => :boolean

  desc "contributions", "Get contributions from user(s)"
  method_option :start_date,
                :type => :string, default: "#{Date.today - 14}",
                :desc => "First date to start counting contributions"
  method_option :end_date,
                :type => :string,
                default: "#{Date.today}",
                :desc => "Last date to count contributions"
  def contributions
    start_date = Date.parse(options[:start_date])
    end_date = Date.parse(options[:end_date])
    get_contributions(start_date, end_date)
  end

  desc "commits", "Adds commits to contributions"
  method_option :repo,
                :type => :string,
                default: "kin/report-service",
                :desc => "Name of the repository you want to get commits for"
  def commits
    repo = options[:repo]
    refresh_commits(repo)
  end
end

GHCC.start(ARGV)
